# Generated by Django 4.0.3 on 2022-03-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('step', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('born_date', models.CharField(blank=True, max_length=128, null=True)),
                ('current_state_education', models.CharField(blank=True, max_length=64, null=True)),
                ('education_place', models.CharField(blank=True, max_length=1024, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=64, null=True)),
                ('address_province', models.CharField(blank=True, max_length=128, null=True)),
                ('address_region_full', models.CharField(blank=True, max_length=128, null=True)),
                ('workplace', models.CharField(blank=True, max_length=512, null=True)),
                ('rank', models.CharField(blank=True, max_length=512, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=512, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
