# Generated by Django 4.0.3 on 2022-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_applicant_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='photo',
        ),
    ]
