# Generated by Django 4.0.3 on 2022-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_applicant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='it_level',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='languages',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='work_experience',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
