# Generated by Django 4.0.3 on 2022-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
