# Generated by Django 4.0.3 on 2022-03-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_userrequest_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='user_id',
            field=models.CharField(default=4231423, max_length=255),
            preserve_default=False,
        ),
    ]
